//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp.DeliveryService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DeliveryService.IDeliveryService")]
    public interface IDeliveryService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeliveryService/GetShipments", ReplyAction="http://tempuri.org/IDeliveryService/GetShipmentsResponse")]
        Data.Database.Shipment[] GetShipments(Data.Database.Truck truck, int skip, int take);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeliveryService/GetShipments", ReplyAction="http://tempuri.org/IDeliveryService/GetShipmentsResponse")]
        System.Threading.Tasks.Task<Data.Database.Shipment[]> GetShipmentsAsync(Data.Database.Truck truck, int skip, int take);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeliveryService/UpdateShipment", ReplyAction="http://tempuri.org/IDeliveryService/UpdateShipmentResponse")]
        void UpdateShipment(Data.Database.Shipment shipment, Data.States.ShipmentState state);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeliveryService/UpdateShipment", ReplyAction="http://tempuri.org/IDeliveryService/UpdateShipmentResponse")]
        System.Threading.Tasks.Task UpdateShipmentAsync(Data.Database.Shipment shipment, Data.States.ShipmentState state);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDeliveryServiceChannel : WpfApp.DeliveryService.IDeliveryService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DeliveryServiceClient : System.ServiceModel.ClientBase<WpfApp.DeliveryService.IDeliveryService>, WpfApp.DeliveryService.IDeliveryService {
        
        public DeliveryServiceClient() {
        }
        
        public DeliveryServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DeliveryServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DeliveryServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DeliveryServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Data.Database.Shipment[] GetShipments(Data.Database.Truck truck, int skip, int take) {
            return base.Channel.GetShipments(truck, skip, take);
        }
        
        public System.Threading.Tasks.Task<Data.Database.Shipment[]> GetShipmentsAsync(Data.Database.Truck truck, int skip, int take) {
            return base.Channel.GetShipmentsAsync(truck, skip, take);
        }
        
        public void UpdateShipment(Data.Database.Shipment shipment, Data.States.ShipmentState state) {
            base.Channel.UpdateShipment(shipment, state);
        }
        
        public System.Threading.Tasks.Task UpdateShipmentAsync(Data.Database.Shipment shipment, Data.States.ShipmentState state) {
            return base.Channel.UpdateShipmentAsync(shipment, state);
        }
    }
}
